name: reve_chat_sdk
description: ReveChat SDK for chat bot support can be added for android and ios platforms
version: 1.0.0
homepage: https://github.com/adhamkhaledabdelwahab/ReveChatSdk

environment:
  sdk: '>=3.0.6 <4.0.0'
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: kh.ad.reve_chat_sdk
        pluginClass: ReveChatSdkPlugin
      ios:
        pluginClass: ReveChatSdkPlugin
